// src/components/ExtractResultCard.svelte
<script lang="ts">
  import { goto } from '@sapper/app'
  import { onMount } from 'svelte'
  import { srcs } from '../store/files'
  import { cxt } from '../store/context'
  import { commonOpt, wordOpt, excelOpt, pptOpt, browserOpt } from '../store/opt'

    let wordSums: number[] = [0]
    let charaSums: number[] = [0]
    let wordTotal: number = 0
    let charaTotal: number = 0
    let downURL: string = ''

    onMount(() => {
      if ($srcs.files.length === 0) {
        goto('/')
      }
      if ($browserOpt.isAutoDown) {
        downFile()
      }
      recalc()
    })

    // function setMode(modeIndex: number): void {
    //   this.$store.commit('setMode', modeIndex)
    // }
    
    function saveInBrowser(): void {
      window.localStorage.setItem('src-content', JSON.stringify($cxt.getRawContent('src')))
    }
    
    function downFile(): void {
      const opq: OptionQue = {
        common: $commonOpt,
        word: $wordOpt,
        excel: $excelOpt,
        ppt: $pptOpt,
      }
      $cxt.getSingleText('src', opq).then((exts) => {
        const merged = exts.join('\n')
        const blob = new Blob([merged], { type: 'text/plain;charset=utf-8' })
        downURL = URL.createObjectURL(blob);
        const link = document.createElement('a')
        link.href = downURL
        link.download = `${$commonOpt.name}.txt`
        link.click()
      })
    }

    function recalc(): void {
      const opq: OptionQue = {
        common: $commonOpt,
        word: $wordOpt,
        excel: $excelOpt,
        ppt: $pptOpt,
      }
      // const wordSums: number[] = []
      // const charaSums: number[] = []
      wordSums = []
      charaSums = []
      const words = $cxt.simpleCalc('word', opq)
      const charas = $cxt.simpleCalc('chara', opq)
      wordTotal = Number(words[1].split('\t')[1])
      charaTotal = Number(charas[1].split('\t')[1])
      // ヘッダー行とサマリー行を読み飛ばすために i = 2 からスタート
      for (let i = 2; i < words.length; i++) {
        const eachWord: number = Number(words[i].split('\t')[1])
        const eachChara: number = Number(charas[i].split('\t')[1])
        wordSums.push(eachWord)
        charaSums.push(eachChara)
      }
    }

    // resetExtractContext(): void {
    //   this.$store.commit('fileIO/resetExtractContext')
    // }
</script>

<div class="card p-5 m-5">
  <header class="card-header">
    <h1 class="card-header-title">抽出結果</h1>
  </header>
  <section class="card-content">
    <table class="table pa-3 is-fullwidth">
      <thead>
        <tr>
          <th>ファイル名</th>
          <th>単語数</th>
          <th>文字数</th>
        </tr>
      </thead>
      <tbody>
        {#each $cxt.getRawContent('src') as ext, idx}
        <tr
          class:is-word = {ext.format === 'docx'}
          class:is-excel = {ext.format === 'xlsx'}
          class:is-ppt = {ext.format === 'pptx'}
        >
          <td>{ ext.name }</td>
          <td class="digit">{ wordSums[idx] } 単語</td>
          <td class="digit">{ charaSums[idx] } 文字</td>
        </tr>
        {/each}
      </tbody>
      <tbody>
        <tr>
          <td>合計</td>
          <td class="digit">{ wordTotal } 単語</td>
          <td class="digit">{ charaTotal } 文字</td>
        </tr>
      </tbody>
    </table>
  </section>
  <section class="card-footer">
    <button class="button card-footer-item" on:click={downFile}>TXT ダウンロード</button>
    <button class="button card-footer-item" on:click={saveInBrowser}>ブラウザに保存</button>
    <button class="button card-footer-item" on:click={recalc}>再計算</button>
    <button class="button card-footer-item" on:click={recalc}>分析へ&gt;&gt;</button>
    <button class="button card-footer-item" on:click={() => goto('/')}>戻る</button>
  </section>
</div>

<style>
.is-word {
  background-color: lightblue;
}

.is-excel {
  background-color: lightgreen;
}

.is-ppt {
  background-color: lightsalmon;
}

td.digit {
  text-align: right;
}
</style>

// src/components/ExtractResultCard.vue
<template>
  <v-card
    class="pa-5 ma-5">
    <v-card-title>抽出結果</v-card-title>
    <v-simple-table
      class="pa-3"
      dense
    >
      <thead>
        <tr>
          <th>ファイル名</th>
          <th>単語数</th>
          <th>文字数</th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="(ext, idx) in $store.state.fileIO.context.src"
          :key="'cons' + idx"
          :class="{
            isWord: ext.format === 'docx',
            isExcel: ext.format === 'xlsx',
            isPpt: ext.format === 'pptx',
          }"
        >
          <td>{{ ext.name }}</td>
          <td class="digit">{{ wordSums[idx] }} 単語</td>
          <td class="digit">{{ charaSums[idx] }} 文字</td>
        </tr>
      </tbody>
      <tbody>
        <tr>
          <td>合計</td>
          <td class="digit">{{ wordTotal }} 単語</td>
          <td class="digit">{{ charaTotal }} 文字</td>
        </tr>
      </tbody>
    </v-simple-table>
    <v-card-actions>
      <v-btn
          class="ma-2"
          color="success"
          @click="downFile"
        >TXT ダウンロード</v-btn>
        <v-btn
          class="ma-2"
          color="secondary"
          @click="saveInBrowser"
        >ブラウザに保存</v-btn>
        <v-btn
          class="ma-2"
          color="info"
          @click="recalc"
        >再計算</v-btn>
        <v-btn
          class="ma-2"
          color="accent"
          @click="setMode(2)"
          to="/"
          nuxt
          outlined
        >分析へ&gt;&gt;</v-btn>
        <v-btn
        class="ma-2"
        color="secondary"
        @click="resetExtractContext"
      >戻る</v-btn>
    </v-card-actions>
  </v-card>
</template>

<script lang="ts">
  import Vue from 'vue'
  import { ExtractedContent } from '../funcs/extract'

  export default Vue.extend({
    data() {
      return {
        wordSums: [0],
        charaSums: [0],
        wordTotal: 0,
        charaTotal: 0,
      }
    },
    created() {
      this.recalc()
    },
    methods: {
      setMode(modeIndex: number) {
        this.$store.commit('setMode', modeIndex)
      },
      saveInBrowser() {
        window.localStorage.setItem('src-context', JSON.stringify(this.$store.state.fileIO.context.getRawContent('src')))
      },
      downFile(): void {
        this.$store.commit('fileIO/downloadClick', 'extract')
        // let link = document.createElement('a')
        // link.href = this.$store.state.fileIO.downurl1
        // link.download = 'extract.txt'
        // link.click()
      },
      recalc() {
        if (this.$store.state.fileIO.context === null) {
          return
        }
        const wordSums: number[] = []
        const charaSums: number[] = []
        const words = this.$store.state.fileIO.context.simpleCalc(
          'word', this.$store.state.fileIO.opt)
        const charas = this.$store.state.fileIO.context.simpleCalc(
          'chara', this.$store.state.fileIO.opt)
        this.wordTotal = Number(words[1].split('\t')[1])
        this.charaTotal = Number(charas[1].split('\t')[1])
        // ヘッダー行とサマリー行を読み飛ばすために i = 2 からスタート
        for (let i = 2; i < words.length; i++) {
          const eachWord: number = Number(words[i].split('\t')[1])
          const eachChara: number = Number(charas[i].split('\t')[1])
          wordSums.push(eachWord)
          charaSums.push(eachChara)
        }
        this.wordSums = wordSums
        this.charaSums = charaSums
      },
      resetExtractContext(): void {
        this.$store.commit('fileIO/resetExtractContext')
      }
    }
  })
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.isWord {
  background-color: lightblue;
}

.isExcel {
  background-color: lightgreen;
}

.isPpt {
  background-color: lightsalmon;
}

td.digit {
  text-align: right;
}
</style>
